---
abstract: 'interpolable HTTP status constants'
author:
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Status-Const
recommends:
  Package::Stash::XS: '0'
requires:
  Const::Exporter: '0'
  Exporter: '0'
  HTTP::Status: '0'
  Package::Stash: '0'
  perl: '5.010'
  version: '0.77'
resources:
  bugtracker: https://github.com/robrwo/HTTP-Status-Constants/issues
  repository: git://github.com/robrwo/HTTP-Status-Constants.git
version: v0.2.2
